# change the host
host: psono.example.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    # change the host
    - host: psono.example.com

server:
  env:
    PSONO_DATABASES_DEFAULT_NAME: psono
    PSONO_DATABASES_DEFAULT_USER: psono
    PSONO_DATABASES_DEFAULT_PASSWORD: test
    PSONO_DATABASES_DEFAULT_HOST: psono-database.psono.svc

    PSONO_SECRET_KEY: 'SOME SUPER SECRET KEY THAT SHOULD BE RANDOM AND 32 OR MORE DIGITS LONG'
    PSONO_ACTIVATION_LINK_SECRET: 'SOME SUPER SECRET ACTIVATION LINK SECRET THAT SHOULD BE RANDOM AND 32 OR MORE DIGITS LONG'
    PSONO_DB_SECRET: 'SOME SUPER SECRET DB SECRET THAT SHOULD BE RANDOM AND 32 OR MORE DIGITS LONG'
    PSONO_EMAIL_SECRET_SALT: '$2b$12$XUG.sKxC2jmkUvWQjg53.e'
    PSONO_PRIVATE_KEY: '302650c3c82f7111c2e8ceb660d32173cdc8c3d7717f1d4f982aad5234648fcb'
    PSONO_PUBLIC_KEY: '02da2ad857321d701d754a7e60d0a147cdbc400ff4465e1f57bc2d9fbfeddf0b'

    PSONO_HOST_URL: 'https://psono.example.com/server'
    PSONO_DEBUG: TRUE
    PSONO_ALLOWED_HOSTS: ['*']
    PSONO_MANAGEMENT_ENABLED: True
    PSONO_FILESERVER_HANDLER_ENABLED: False
    PSONO_FILES_ENABLED: False
    PSONO_ALLOW_USER_SEARCH_BY_USERNAME_PARTIAL: False
    PSONO_ALLOW_USER_SEARCH_BY_EMAIL: false
    PSONO_ALLOW_REGISTRATION: True
    PSONO_ENFORCE_MATCHING_USERNAME_AND_EMAIL: False
    PSONO_ALLOWED_DOMAINS: ['example.com']
    PSONO_EMAIL_FROM: 'psono@example.com'
    PSONO_EMAIL_HOST: 'mail.psono.svc'
    PSONO_EMAIL_PORT: 587
    PSONO_EMAIL_USE_TLS: False
    PSONO_EMAIL_USE_SSL: False
    PSONO_EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'

webclient:
  env:
    PSONO_WEBCLIENT_CONFIG_JSON: |
      {
        "backend_servers": [{
          "title": "psono.pw",
          "domain": "example.com",
          "url": "https://psono.example.com/server"
        }],
        "base_url": "https://psono.example.com/",
        "allow_custom_server": true,
        "allow_registration": true,
        "allow_lost_password": true,
        "disable_download_bar": false,
        "authentication_methods": ["AUTHKEY"]
      }

adminClient:
  env:
    PSONO_PORTAL_CONFIG_JSON: |
      {
        "backend_servers": [{
          "title": "psono.pw",
          "domain": "example.com",
          "url": "https://psono.example.com/server"
        }],
        "base_url": "https://psono.example.com/",
        "allow_custom_server": true,
        "allow_registration": true,
        "allow_lost_password": true,
        "disable_download_bar": false,
        "authentication_methods": ["AUTHKEY"]
      }

database:
  env:
    POSTGRES_PASSWORD: test
    POSTGRES_USER: psono
    POSTGRES_DB: psono

mail:
  enabled: true
  persistence:
    enabled: false
  
  config:
    general:
      ALLOWED_SENDER_DOMAINS: tiagoposse.com